#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = "Terminal ({{ .Shell }})"

[palette]
  execution_time = "yellow"
  nix_shell = "yellow"
  path = "blue"
  git = "#6c6c6c"
  
  normal = "magenta"
  error = "red"

# Path & Git line
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  # Path
  [[blocks.segments]]
    type = "path"
    style = "plain"
    
    background = "transparent"
    foreground = "p:path"
    
    template = '{{ if matchP "^[^~/]" .Path }}/{{ end }}{{ .Path }}' # Fix when at /, the / doesnt show.

    [blocks.segments.properties]
      style = "mixed"
      mixed_threshold = 25
      folder_icon = "…"

  # Git
  [[blocks.segments]]
    type = "git"
    style = "plain"
    
    foreground = "p:git"
    background = "transparent"
    
    template = " {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>"

    [blocks.segments.properties]
      branch_icon = ""
      commit_icon = "@"
      fetch_status = true

  # Force the bar cursor type (|)
  [[blocks.segments]]
    type = "command"
    style = "plain"
    template = "{{ .Output }}"
    
    [blocks.segments.properties]
      command = "printf '\\033[5 q'"

# Execution time
[[blocks]]
  type = "rprompt"
  overflow = "hidden"

  [[blocks.segments]]
    type = "executiontime"
    style = "plain"
    
    foreground = "p:execution_time"
    background = "transparent"
    
    template = "{{ .FormattedMs }}"

    [blocks.segments.properties]
      style = "round"
      threshold = 5000

# Prompt
[[blocks]]
  type = "prompt"
  alignment = "left"
  newline = true

  [[blocks.segments]]
    type = "text"
    style = "plain"
    
    foreground = "p:normal"
    foreground_templates = [
      "{{ if gt .Code 0 }}p:error{{ end }}",
      "{{ if .Env.IN_NIX_SHELL }}p:nix_shell{{ end }}"
    ]
    background = "transparent"
    
    template = "❯"

# Transient Prompt
[transient_prompt]
  foreground = "p:normal"
  foreground_templates = [
    "{{ if gt .Code 0 }}p:error{{ end }}",
    "{{ if .Env.IN_NIX_SHELL }}p:nix_shell{{ end }}"
  ]
  background = "transparent"
  
  template = "❯ "

# Secondary Prompt
[secondary_prompt]
  foreground = "p:normal"
  foreground_template = "{{ if .Env.IN_NIX_SHELL }}p:nix_shell{{ end }}"
  background = "transparent"
  
  template = "❯❯ "
